version: '3'

services:

  jenkins:
    image: 'jenkins/jenkins:lts'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - './data:/var/jenkins_home'